/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SecurityCheckRouteImport } from './routes/security-check'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as FinancesRouteImport } from './routes/finances'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AddMoneyRouteImport } from './routes/add-money'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SecurityCheckIndexRouteImport } from './routes/security-check.index'
import { Route as AddMoneyIndexRouteImport } from './routes/add-money.index'
import { Route as SecurityCheckConfirmedRouteImport } from './routes/security-check.confirmed'
import { Route as SecurityCheckCodeRouteImport } from './routes/security-check.code'
import { Route as AddMoneySuccessRouteImport } from './routes/add-money.success'
import { Route as AddMoneyMethodRouteImport } from './routes/add-money.method'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityCheckRoute = SecurityCheckRouteImport.update({
  id: '/security-check',
  path: '/security-check',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancesRoute = FinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AddMoneyRoute = AddMoneyRouteImport.update({
  id: '/add-money',
  path: '/add-money',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityCheckIndexRoute = SecurityCheckIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SecurityCheckRoute,
} as any)
const AddMoneyIndexRoute = AddMoneyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AddMoneyRoute,
} as any)
const SecurityCheckConfirmedRoute = SecurityCheckConfirmedRouteImport.update({
  id: '/confirmed',
  path: '/confirmed',
  getParentRoute: () => SecurityCheckRoute,
} as any)
const SecurityCheckCodeRoute = SecurityCheckCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => SecurityCheckRoute,
} as any)
const AddMoneySuccessRoute = AddMoneySuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => AddMoneyRoute,
} as any)
const AddMoneyMethodRoute = AddMoneyMethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => AddMoneyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-money': typeof AddMoneyRouteWithChildren
  '/auth': typeof AuthRoute
  '/deals': typeof DealsRoute
  '/finances': typeof FinancesRoute
  '/payments': typeof PaymentsRoute
  '/security-check': typeof SecurityCheckRouteWithChildren
  '/wallet': typeof WalletRoute
  '/add-money/method': typeof AddMoneyMethodRoute
  '/add-money/success': typeof AddMoneySuccessRoute
  '/security-check/code': typeof SecurityCheckCodeRoute
  '/security-check/confirmed': typeof SecurityCheckConfirmedRoute
  '/add-money/': typeof AddMoneyIndexRoute
  '/security-check/': typeof SecurityCheckIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/deals': typeof DealsRoute
  '/finances': typeof FinancesRoute
  '/payments': typeof PaymentsRoute
  '/wallet': typeof WalletRoute
  '/add-money/method': typeof AddMoneyMethodRoute
  '/add-money/success': typeof AddMoneySuccessRoute
  '/security-check/code': typeof SecurityCheckCodeRoute
  '/security-check/confirmed': typeof SecurityCheckConfirmedRoute
  '/add-money': typeof AddMoneyIndexRoute
  '/security-check': typeof SecurityCheckIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-money': typeof AddMoneyRouteWithChildren
  '/auth': typeof AuthRoute
  '/deals': typeof DealsRoute
  '/finances': typeof FinancesRoute
  '/payments': typeof PaymentsRoute
  '/security-check': typeof SecurityCheckRouteWithChildren
  '/wallet': typeof WalletRoute
  '/add-money/method': typeof AddMoneyMethodRoute
  '/add-money/success': typeof AddMoneySuccessRoute
  '/security-check/code': typeof SecurityCheckCodeRoute
  '/security-check/confirmed': typeof SecurityCheckConfirmedRoute
  '/add-money/': typeof AddMoneyIndexRoute
  '/security-check/': typeof SecurityCheckIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-money'
    | '/auth'
    | '/deals'
    | '/finances'
    | '/payments'
    | '/security-check'
    | '/wallet'
    | '/add-money/method'
    | '/add-money/success'
    | '/security-check/code'
    | '/security-check/confirmed'
    | '/add-money/'
    | '/security-check/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/deals'
    | '/finances'
    | '/payments'
    | '/wallet'
    | '/add-money/method'
    | '/add-money/success'
    | '/security-check/code'
    | '/security-check/confirmed'
    | '/add-money'
    | '/security-check'
  id:
    | '__root__'
    | '/'
    | '/add-money'
    | '/auth'
    | '/deals'
    | '/finances'
    | '/payments'
    | '/security-check'
    | '/wallet'
    | '/add-money/method'
    | '/add-money/success'
    | '/security-check/code'
    | '/security-check/confirmed'
    | '/add-money/'
    | '/security-check/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddMoneyRoute: typeof AddMoneyRouteWithChildren
  AuthRoute: typeof AuthRoute
  DealsRoute: typeof DealsRoute
  FinancesRoute: typeof FinancesRoute
  PaymentsRoute: typeof PaymentsRoute
  SecurityCheckRoute: typeof SecurityCheckRouteWithChildren
  WalletRoute: typeof WalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security-check': {
      id: '/security-check'
      path: '/security-check'
      fullPath: '/security-check'
      preLoaderRoute: typeof SecurityCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finances': {
      id: '/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof FinancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-money': {
      id: '/add-money'
      path: '/add-money'
      fullPath: '/add-money'
      preLoaderRoute: typeof AddMoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security-check/': {
      id: '/security-check/'
      path: '/'
      fullPath: '/security-check/'
      preLoaderRoute: typeof SecurityCheckIndexRouteImport
      parentRoute: typeof SecurityCheckRoute
    }
    '/add-money/': {
      id: '/add-money/'
      path: '/'
      fullPath: '/add-money/'
      preLoaderRoute: typeof AddMoneyIndexRouteImport
      parentRoute: typeof AddMoneyRoute
    }
    '/security-check/confirmed': {
      id: '/security-check/confirmed'
      path: '/confirmed'
      fullPath: '/security-check/confirmed'
      preLoaderRoute: typeof SecurityCheckConfirmedRouteImport
      parentRoute: typeof SecurityCheckRoute
    }
    '/security-check/code': {
      id: '/security-check/code'
      path: '/code'
      fullPath: '/security-check/code'
      preLoaderRoute: typeof SecurityCheckCodeRouteImport
      parentRoute: typeof SecurityCheckRoute
    }
    '/add-money/success': {
      id: '/add-money/success'
      path: '/success'
      fullPath: '/add-money/success'
      preLoaderRoute: typeof AddMoneySuccessRouteImport
      parentRoute: typeof AddMoneyRoute
    }
    '/add-money/method': {
      id: '/add-money/method'
      path: '/method'
      fullPath: '/add-money/method'
      preLoaderRoute: typeof AddMoneyMethodRouteImport
      parentRoute: typeof AddMoneyRoute
    }
  }
}

interface AddMoneyRouteChildren {
  AddMoneyMethodRoute: typeof AddMoneyMethodRoute
  AddMoneySuccessRoute: typeof AddMoneySuccessRoute
  AddMoneyIndexRoute: typeof AddMoneyIndexRoute
}

const AddMoneyRouteChildren: AddMoneyRouteChildren = {
  AddMoneyMethodRoute: AddMoneyMethodRoute,
  AddMoneySuccessRoute: AddMoneySuccessRoute,
  AddMoneyIndexRoute: AddMoneyIndexRoute,
}

const AddMoneyRouteWithChildren = AddMoneyRoute._addFileChildren(
  AddMoneyRouteChildren,
)

interface SecurityCheckRouteChildren {
  SecurityCheckCodeRoute: typeof SecurityCheckCodeRoute
  SecurityCheckConfirmedRoute: typeof SecurityCheckConfirmedRoute
  SecurityCheckIndexRoute: typeof SecurityCheckIndexRoute
}

const SecurityCheckRouteChildren: SecurityCheckRouteChildren = {
  SecurityCheckCodeRoute: SecurityCheckCodeRoute,
  SecurityCheckConfirmedRoute: SecurityCheckConfirmedRoute,
  SecurityCheckIndexRoute: SecurityCheckIndexRoute,
}

const SecurityCheckRouteWithChildren = SecurityCheckRoute._addFileChildren(
  SecurityCheckRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddMoneyRoute: AddMoneyRouteWithChildren,
  AuthRoute: AuthRoute,
  DealsRoute: DealsRoute,
  FinancesRoute: FinancesRoute,
  PaymentsRoute: PaymentsRoute,
  SecurityCheckRoute: SecurityCheckRouteWithChildren,
  WalletRoute: WalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
